bikesharing/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic.base import RedirectView

from rest_framework.authtoken.views import obtain_auth_token

from . import settings
from .utils.routers import router

# Wire up our API using automatic URL routing.
# Additionally, we include login URLs for the browsable API.
urlpatterns = [
    path("", RedirectView.as_view(url="home/")),
    path("admin/", admin.site.urls),
    path("router/", include(router.urls)),
    path("auth/", obtain_auth_token),
    path("api-auth/", include("rest_framework.urls", namespace="rest_framework")),
    path("home/", include("home.urls", namespace="home")),
    path("user/", include("user.urls", namespace="registrasi")),
    path("transaction/", include("transaction.urls", namespace="transaction")),
    path("report/", include("report.urls", namespace="report")),
    path("acara/", include("acara.urls", namespace="acara")),
    path("penugasan/", include("penugasan.urls", namespace="penugasan")),
    path("voucher/", include("voucher.urls", namespace="voucher")),
    path("peminjaman/", include("peminjaman.urls", namespace="peminjaman")),
    path("sepeda/", include("sepeda.urls", namespace="sepeda")),
    path("stasiun/", include("stasiun.urls", namespace="stasiun")),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
        path("__debug__/", include(debug_toolbar.urls)),
        # For django versions before 2.0:
        # url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

home/urls.py
from django.urls import path
from .views import index

app_name = 'home'
urlpatterns = [
    path('', index, name='home')
]

stasiun/urls.py
from django.urls import path
from .views import add_stasiun, stasiun_lists, StasiunAPI

app_name = 'stasiun'
urlpatterns = [
    path('api/', StasiunAPI.as_view()),
    path('add/', add_stasiun, name='stasiun'),
    path('', stasiun_lists, name='stasiun_lists'),
]

stasiun/models.py
from django.db import models

# Create your models here.
class Stasiun_models(models.Model):
	nama = models.CharField(primary_key=True, max_length=10)
	alamat = models.CharField(max_length=50)
	latitude = models.CharField(max_length=50)
	longitude = models.CharField(max_length=50)
	class Meta:
		db_table = 'STASIUN'

stasiun/forms.py
from django import forms
from .models import Stasiun_models

class stasiun_forms(forms.Form):
    attrs = {
        'class': 'form-control'
    }

    nama = forms.CharField(label = "Nama", max_length= 10, required=True, widget = forms.TextInput(attrs = attrs))
    alamat = forms.CharField(label = "Alamat", max_length=50, required=True, widget = forms.TextInput(attrs = attrs))
    latitude = forms.CharField(label = "Latitude", max_length = 50, required=True, widget = forms.TextInput(attrs = attrs))
    longitude = forms.CharField(label = "Longitude", max_length = 50, required=True, widget = forms.TextInput(attrs = attrs))

stasiun/views.py
from django.shortcuts import render
from django.db import connection
from django.http import HttpResponseRedirect, HttpResponse, JsonResponse
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework.permissions import IsAuthenticated
from rest_framework.authentication import TokenAuthentication
from user.utils import ConnectDB
from datetime import datetime
import requests
import random

# Create your views here.
def stasiun_regis(request):
	return render(request, 'stasiun.html')

# def stasiun_lists(request):
# 	return render(request, 'stasiun_lists.html')

class StasiunAPI(APIView):
    permission_classes = (IsAuthenticated,)
    authentication_classes = (TokenAuthentication,)

    def get(self, request):
        user = request.user
        data = ConnectDB.getAllDataWithQuery(
                '''
                SELECT * FROM stasiun
                '''
            )
        return Response(data)

def stasiun_lists(request):
    person = ConnectDB.getUserDataWithApi(request)
    response = ConnectDB.getPersonalDataWithApi(request, 'stasiun', '/stasiun/api/')
    print(response)
    response.update(person)
    return render(request, 'stasiun.html', response)

def add_stasiun(request):
    if (request.method == "POST"):
        id = random.randint(0, 100000)
        nama = request.POST.get('nama', None)
        alamat = request.POST.get('alamat', None)
        latitude = request.POST.get('latitude', None)
        longitude = request.POST.get('longitude', None)
        with connection.cursor() as cursor:
            cursor.execute("INSERT INTO stasiun VALUES(%s, %s, %s, %s, %s)", [
                id, alamat, latitude, longitude, nama])
        return HttpResponse("SUCCESS 200")
    else:
        return HttpResponse("HTTP 204")

stasiun/templates/stasiun.component.html
{% if stasiun|length > 0 %}
<table class="table" style="margin: 10 10 10 auto;">
    <thead>
    <tr>
        <th scope="col">No</th>
        <th scope="col">Station Name</th>
        <th scope="col">Address</th>
        <th scope="col">Latitude</th>
        <th scope="col">Longitude</th>

        {% if role == "ADMIN" %}
        <th scope="col">Action</th>
        {% endif %}
    </tr>
    </thead>
    <tbody>

    {% for data in stasiun %}
    <tr>
        <td>{{ data.id_stasiun }}</td>
        <td>{{ data.nama }}</td>
        <td>{{ data.alamat }}</td>
        <td>{{ data.lat }}</td>
        <td>{{ data.long }}</td>
        {% if role == "ADMIN" %}
        <td class="col">
            <button class="btn red">Delete</button>
            <button class="btn orange">Update</button>
        </td>
        {% endif %}
    </tr>
    {% endfor %}

    </tbody>
</table>

{% else %}
<div class="flex-center">
<p>Tidak ada stasiun.</p>
</div>
{% endif %}

stasiun/templates/stasiun.html
{% extends 'sidebar.html' %}
{% load static %}
{% load staticfiles%}

{% block content %}

<div class="row">
  <div class="col grid">
    <div id="riwayat-transaksi" class="card">
      <h1 id="title">Stasiun</h1>
      {% include 'stasiun.component.html' %}
    </div>
  </div>
</div>

{% if role == "ADMIN" %}
<div id="modal-container" class="modal">
  <div class="modal-content">
    <form method="POST">
        {% csrf_token %}
        <div class="form-group"><label for="id_stasiun">Station Name</label><input type="text"
        class="form-control" id="id_stasiun" placeholder="Enter the name..." /></div>

        <div class="form-group"><label for="id_address">Address</label><input type="text"
        class="form-control" id="id_address" placeholder="Enter the address..." /></div>

        <div class="form-group"><label for="id_latitude">Latitude</label><input type="number"
        class="form-control" id="id_latitude" placeholder="Enter the latitude..." /></div>

        <div class="form-group"><label for="id_longitude">Longitude</label><input type="number"
        class="form-control" id="id_longitude" placeholder="Enter the Longitude..." /></div>
      </form>
      <button id="submit" class="btn green m-1">Add</button>
    </div>
  </div>
</div>

<div class=" circle ripple modal-btn" data-target="modal-container" data-color="white" id="add-btn">
  <i id="add" class="material-icons md-light">add</i>
</div>
{% endif %}
  <script src="{% static 'js/stasiun.js' %}"></script>
{% endblock %}