bikesharing/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic.base import RedirectView

from rest_framework.authtoken.views import obtain_auth_token

from . import settings
from .utils.routers import router

# Wire up our API using automatic URL routing.
# Additionally, we include login URLs for the browsable API.
urlpatterns = [
    path("", RedirectView.as_view(url="home/")),
    path("admin/", admin.site.urls),
    path("router/", include(router.urls)),
    path("auth/", obtain_auth_token),
    path("api-auth/", include("rest_framework.urls", namespace="rest_framework")),
    path("home/", include("home.urls", namespace="home")),
    path("user/", include("user.urls", namespace="registrasi")),
    path("transaction/", include("transaction.urls", namespace="transaction")),
    path("report/", include("report.urls", namespace="report")),
    path("acara/", include("acara.urls", namespace="acara")),
    path("penugasan/", include("penugasan.urls", namespace="penugasan")),
    path("voucher/", include("voucher.urls", namespace="voucher")),
    path("peminjaman/", include("peminjaman.urls", namespace="peminjaman")),
    path("sepeda/", include("sepeda.urls", namespace="sepeda")),
    path("stasiun/", include("stasiun.urls", namespace="stasiun")),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
        path("__debug__/", include(debug_toolbar.urls)),
        # For django versions before 2.0:
        # url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

home/urls.py
from django.urls import path
from .views import index

app_name = 'home'
urlpatterns = [
    path('', index, name='home')
]

sepeda/urls.py
from django.urls import path
from .views import add_sepeda, delete_sepeda, update_sepeda, sepeda_lists, SepedaAPI

app_name = 'sepeda'
urlpatterns = [
    path('add/', add_sepeda, name='sepeda'),
    path('', sepeda_lists, name='sepeda_lists'),
    path('api/', SepedaAPI.as_view()),
    path('delete/', delete_sepeda, name='delete_sepeda'),
    path('update/', update_sepeda, name='update_sepeda')
]

sepeda/models.py
from django.db import models

class Sepeda_models(models.Model):
	merk = models.CharField(primary_key=True, max_length=10)
	jenis = models.CharField(max_length=50)
	status = models.CharField(max_length=50)
	stasiun = models.CharField(max_length=10)
	penyumbang = models.CharField(max_length=20)
	class Meta:
		db_table = 'SEPEDA'

sepeda/views.py
from django.shortcuts import render
from django.db import connection
from django.http import HttpResponseRedirect, HttpResponse, JsonResponse
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework.permissions import IsAuthenticated
from rest_framework.authentication import TokenAuthentication
from user.utils import ConnectDB
from datetime import datetime
import requests
import random

# Create your views here.
def sepeda_regist(request):
	return render(request, 'sepeda.html')

# def sepeda_lists(request):
#     return render(request, 'sepeda_lists.html')

class SepedaAPI(APIView):
    permission_classes = (IsAuthenticated,)
    authentication_classes = (TokenAuthentication,)

    def get(self, request):
        user = request.user
        data = ConnectDB.getAllDataWithQuery(
                '''
                SELECT * FROM sepeda
                '''
            )
        return Response(data)


def sepeda_lists(request):
    person = ConnectDB.getUserDataWithApi(request)
    response = ConnectDB.getPersonalDataWithApi(request, 'sepeda', '/sepeda/api/')
    print(response)
    response.update(person)
    return render(request, 'sepeda.html', response)

def add_sepeda(request):
    if (request.method == "POST"):
        nomor = random.randint(0, 100000)
        merk = request.POST.get('brand', None)
        jenis = request.POST.get('type', None)
        status = request.POST.get('status', None)
        stasiun = request.POST.get('station', None)
        penyumbang = request.POST.get('pendonor', None)
        with connection.cursor() as cursor:
            cursor.execute("INSERT INTO sepeda VALUES(%s, %s, %s, %s, %s, %s)", [
                nomor, merk, jenis, status, stasiun, penyumbang])
        return HttpResponse("SUCCESS 200")
    else:
        return HttpResponse("HTTP 204")

def delete_sepeda(request):
    if (request.method == "POST"):
        nomor = request.POST.get('number', None)
        with connection.cursor() as cursor:
            cursor.execute("DELETE from sepeda WHERE nomor=%s", [nomor])
        return HttpResponse("SUCCESS 200")
    else:
        return HttpResponse("HTTP 204")

def update_sepeda(request):
    if (request.method == "POST"):
        nomor = request.POST.get('number', None)
        merk = request.POST.get('brand', None)
        jenis = request.POST.get('type', None)
        status = request.POST.get('status', None)
        stasiun = request.POST.get('station', None)
        penyumbang = request.POST.get('pendonor', None)
        with connection.cursor() as cursor:
            cursor.execute('''
            UPDATE sepeda 
            SET merk=%s, jenis=%s, status=%s, id_stasiun=%s, no_kartu_penyumbang=%s
            WHERE nomor=%s
            ''', [merk, jenis, status, stasiun, penyumbang, nomor])
        return HttpResponse("SUCCESS 200")
    else:
        return HttpResponse("HTTP 204")

sepeda/templates/sepeda.component.html
      {% if sepeda|length > 0 %}
        <table class="table" style="margin: 10 10 10 auto;">
          <thead>
            <tr>
              <th scope="col">No</th>
              <th scope="col">Brand</th>
              <th scope="col">Type</th>
              <th scope="col">Station</th>
              <th scope="col">Status</th>
              <th scope="col">Donor</th>

              {% if role == "ADMIN" %}
              <th scope="col">Action</th>
              {% endif %}

            </tr>
          </thead>
          <tbody>
            {% for data in sepeda %}
            <tr>
              <td>{{ data.nomor }}</td>
              <td>{{ data.merk }}</td>
              <td>{{ data.jenis }}</td>
              <td>{{ data.id_stasiun}}</td>
              {% if data.status == "True" %}
              <td>Tersedia</td>
              {% else %}
              <td>Tidak Tersedia</td>
              {% endif %}
              <td>{{ data.no_kartu_penyumbang }}</td>
              {% if role == "ADMIN" %}
              <td class="col">
                <button id={{ data.nomor }} class="btn red delete">Delete</button>
                <button id={{ data.nomor }} class="btn orange update modal-update" data-target="modal-update">Update</button>
              </td>
              {% endif %}
            </tr>
            {% endfor %}
          </tbody>
        </table>

        {% else %}
        <div class="flex-center">
          <p>Tidak ada sepeda.</p>
        </div>
        {% endif %}

{% if role == "ADMIN" %}
<div id="modal-update" class="modal">
  <div class="modal-content">
    <h3 id="nomor-update"></h3>
    <form method="post">
      {% csrf_token %}
        <div class="form-group"><label for="id_brand_update">Brand</label><input type="text"
        class="form-control" id="id_brand_update" placeholder="Enter the brand..." /></div>

        <div class="form-group"><label for="id_type_update">Type</label><input type="text"
        class="form-control" id="id_type_update" placeholder="Enter the type..." /></div>

        <div class="form-group">
            <label for="id_status_update">Status</label>
            <select id="id_status_update" class="form-control" class="ui fluid dropdown">
                <option hidden value="">Status</option>
                <option value="Tersedia">Tersedia</option>
                <option value="Tidak tersedia">Tidak tersedia</option>
            </select>
        </div>
        <div class="form-group"><label for="id_station_update">Station</label><input type="text"
            class="form-control" id="id_station_update" placeholder="Enter the Station..." /></div>
            <div class="form-group"><label for="id_pendonor_update">Donor Card Number</label><input type="text"
                class="form-control" id="id_pendonor_update" placeholder="Enter the Donor name..." /></div>
        </form>
        <button id="update-form" class="btn orange">Update</button>
    </div>
  </div>
</div>
{% endif %}

sepeda/templates/sepeda.html
 {% extends 'sidebar.html' %}
{% load static %}
{% load staticfiles%}

{% block content %}

<div class="row">
  <div class="col grid">
    <div id="riwayat-transaksi" class="card">
      <h1 id="title">Sepeda</h1>
      {% include 'sepeda.component.html' %}
    </div>
  </div>
</div>

{% if role == "ADMIN" %}
<div id="modal-container" class="modal">
  <div class="modal-content">
    <form method="post">
      {% csrf_token %}
        <div class="form-group"><label for="id_brand">Brand</label><input type="text"
        class="form-control" id="id_brand" placeholder="Enter the brand..." /></div>

        <div class="form-group"><label for="id_type">Type</label><input type="text"
        class="form-control" id="id_type" placeholder="Enter the type..." /></div>

        <div class="form-group">
            <label for="id_status">Status</label>
            <select id="id_status" class="form-control" class="ui fluid dropdown">
                <option hidden value="">Status</option>
                <option value="Tersedia">Tersedia</option>
                <option value="Tidak tersedia">Tidak tersedia</option>
            </select>
        </div>
        <div class="form-group"><label for="id_station">Station</label><input type="text"
            class="form-control" id="id_station" placeholder="Enter the Station..." /></div>
            
            <div class="form-group"><label for="id_pendonor">Donor Card Number</label><input type="text"
                class="form-control" id="id_pendonor" placeholder="Enter the Donor name..." /></div>
        </form>
        <button id="submit" class="btn green m-1">Add</button>
    </div>
  </div>
</div>

<div class=" circle ripple modal-btn" data-target="modal-container" data-color="white" id="add-btn">
  <i id="add" class="material-icons md-light">add</i>
</div>
{% endif %}
  <script src="{% static 'js/sepeda.js' %}"></script>
{% endblock %}